// Generated by CoffeeScript 1.7.1
(function() {
  app.pageName = 'books';

  app.layouts = [
    {
      title: 'THE LIVING BIRD',
      slug: 'TheLivingBird',
      text: ['Visual and experiential journey of the century-long<br>work by the Cornell Lab of Ornithology'],
      publisher: 'MOUNTAINEERS BOOKS',
      image_count: 2
    }, {
      title: 'THE MAP AS ART',
      slug: 'TheMapAsArt',
      text: ['Collection of contemporary art<br>exploring cartography'],
      publisher: 'PRINCETON ARCHITECTURAL PRESS',
      image_count: 2
    }, {
      title: 'YOU ARE HERE',
      slug: 'YouAreHere',
      text: ['Maps of personal geography<br>and realms of fantasy'],
      publisher: 'PRINCETON ARCHITECTURAL PRESS',
      image_count: 2
    }, {
      title: 'WHERE WATER IS GOLD',
      slug: 'WhereWaterIsGold',
      text: ['Book illuminating the national treasure<br>that is Bristol Bay, Alaska'],
      publisher: 'BRAIDED RIVER',
      image_count: 2
    }, {
      title: 'BLACKSTOCK\'S COLLECTIONS',
      slug: 'BlackstocksCollections',
      text: ['Drawings of an autistic artist', '2006 BEST IN SHOW Award Winner<br>Publishers Association of the West'],
      publisher: 'PRINCETON ARCHITECTURAL PRESS',
      image_count: 2
    }, {
      title: 'TRAVELS TO THE EDGE',
      slug: 'TravelsToTheEdge',
      text: ['Awe-inspiring places, cultures and creatures, captured by Art Wolfe', 'Companion piece to 13-episode public television series'],
      publisher: 'MOUNTAINEERS BOOKS',
      image_count: 2
    }, {
      title: 'THE LAST POLAR BEAR',
      slug: 'TheLastPolarBear',
      text: ['Photographs and essays connecting the polar bear\'s uncertain future and climate change'],
      publisher: 'BRAIDED RIVER',
      image_count: 2
    }, {
      title: 'ICE BEAR',
      slug: 'IceBear',
      text: ['Photographic portrait of the polar bear’s Arctic home and life cycle'],
      publisher: 'MOUNTAINEERS BOOKS',
      image_count: 2
    }, {
      title: 'SALMON IN THE TREES',
      slug: 'SalmonInTheTrees',
      text: ['Story of the Tongass rain forest of Alaska<br>one of the rarest ecosystems on Earth'],
      publisher: 'BRAIDED RIVER',
      image_count: 2
    }, {
      title: 'ON ARCTIC GROUND',
      slug: 'OnArcticGround',
      text: ['Platform to raise awareness<br>for preserving significant areas<br>in the Arctic National Petroleum Reserve'],
      publisher: 'BRAIDED RIVER',
      image_count: 2
    }, {
      title: 'PLANET ICE',
      slug: 'PlanetIce',
      text: ['Photographic account of the rapidly changing<br>ice on Earth', '2009 CHOICE AWARD<br>Atmospheric Science Librarians International'],
      publisher: 'Braided River',
      image_count: 2
    }, {
      title: 'RESURRECTION',
      slug: 'Resurrection',
      text: ['A call for action in response to Glen Canyon\'s reappearance from Lake Powell'],
      publisher: 'BRAIDED RIVER',
      image_count: 2
    }, {
      title: 'COLUMBIA HIGHLANDS',
      slug: 'ColumbiaHighlands',
      text: ['A celebration of the beauty and treasure<br>of northeastern Washington State'],
      publisher: 'BRAIDED RIVER',
      image_count: 2
    }, {
      title: 'UP TO NO GOOD',
      slug: 'UpToNoGood',
      text: ['Collection of stories and photographs of bad boys'],
      publisher: 'CHRONICLE BOOKS',
      image_count: 2
    }, {
      title: 'CLOSER TO WILDNESS',
      slug: 'CloserToWildness',
      text: ['Collection of art and musings<br>of Irene Hardwicke Olivieri'],
      publisher: '',
      image_count: 2
    }, {
      title: 'MACRO PHOTOGRAPHY',
      slug: 'MacroPhotography',
      text: ['Guide to photographing plant life up close'],
      publisher: 'TIMBER PRESS',
      image_count: 2
    }, {
      title: 'SAGE SPIRIT',
      slug: 'SageSpirit',
      text: ['Insight into the health of an ecosystem<br>on which greater sage grouse depend'],
      publisher: 'BRAIDED RIVER',
      image_count: 2
    }, {
      title: 'THE WILDEST ROCKIES',
      slug: 'TheWildestRockies',
      text: ['Celebration of northern Montana<br>and southern Alberta, known<br>as the “Crown of the Continent” '],
      publisher: 'BRAIDED RIVER',
      image_count: 2
    }, {
      title: 'EVEREST: THE WEST RIDGE',
      slug: 'EverestWestRidge',
      text: ['Special anniversary edition to commemorate<br>the 50th anniversary of the first ascent<br>of Mount Everest via the West Ridge'],
      publisher: 'MOUNTAINEERS BOOKS',
      image_count: 2
    }, {
      title: 'REAL GARDENS GROW NATIVES',
      slug: 'RealGardens',
      text: ['Accessible yet comprehensive advice<br>for integrating natives, edibles,<br>and non-native ornamentals in your garden'],
      publisher: 'SKIPSTONE',
      image_count: 1
    }, {
      title: 'THE REVOLUTIONARY YARDSCAPE',
      slug: 'TheRevolutionaryYardscape',
      text: ['Ideas for repurposing local materials<br>to create containers, pathways, and lighting', '2011 GOLD MEDAL Design Winner<br>Garden Writer\'s Association'],
      publisher: 'TIMBER PRESS',
      image_count: 2
    }, {
      title: 'BUY THIS BOOK QUENCH A THIRST',
      slug: 'BuyThisBook',
      text: ['Documenting the importance of access to clean drinking water around the globe<br>(in development)'],
      publisher: 'TRIBUTARY BOOKS',
      image_count: 1
    }, {
      title: 'THE COMPLETE CHILE PEPPER BOOK',
      slug: 'ChilePepper',
      text: ['Comprehensive guide to choosing, growing, preserving, and cooking chile peppers'],
      publisher: 'TIMBER PRESS',
      image_count: 2
    }, {
      title: 'FOOD GROWN RIGHT, IN YOUR BACKYARD',
      slug: 'FoodGrownRight',
      text: ['Guide to building a garden from<br>the ground up'],
      publisher: 'SKIPSTONE',
      image_count: 2
    }, {
      title: 'THE FRONT YARD FORAGER',
      slug: 'FrontYardForager',
      text: ['Field guide and recipe book showcasing<br>readily found edible urban weeds'],
      publisher: 'SKIPSTONE',
      image_count: 1
    }, {
      title: 'CITY GOATS',
      slug: 'CityGoats',
      text: ['How-to and benefits of keeping and raising milking goats on your city lot'],
      publisher: 'SKIPSTONE',
      image_count: 1
    }, {
      title: 'POTS IN THE GARDEN',
      slug: 'PotsGarden',
      text: ['Design and planting techniques<br>for using pots in the garden'],
      publisher: 'TIMBER PRESS',
      image_count: 2
    }, {
      title: 'COLEUS',
      slug: 'Coleus',
      text: ['Guide to designing with and caring for coleus, including an encyclopedia of 225 varieties'],
      publisher: 'TIMBER PRESS',
      image_count: 2
    }, {
      title: 'GROWING THE MIDWEST GARDEN',
      slug: 'GrowingMidwestGarden',
      text: ['Encyclopedic guide to plants specifically<br>suited to the heartland'],
      publisher: 'TIMBER PRESS',
      image_count: 2
    }, {
      title: 'THE GUIDE TO WEST COAST CHEESE',
      slug: 'WestCoastCheese',
      text: ['Reference for selecting, identifying,<br>and savoring<br>the cheeses of California,<br>Oregon, and Washington'],
      publisher: 'TIMBER PRESS',
      image_count: 2
    }, {
      title: 'URBAN PANTRY',
      slug: 'UrbanPantry',
      text: ['Guide to making better use of kitchen, garden and time for the modern audience'],
      publisher: 'SKIPSTONE',
      image_count: 2
    }, {
      title: 'EDIBLE HEIRLOOMS',
      slug: 'EdibleHeirlooms',
      text: ['Guide to growing heritage vegetables<br>for the maritime garden'],
      publisher: 'MOUNTAINEERS BOOKS',
      image_count: 2
    }, {
      title: 'NORTHWEST FORAGING',
      slug: 'NorthwestForaging',
      text: ['Update of a classic guide to identifying<br>and harvesting wild edible plants'],
      publisher: 'MOUNTAINEERS BOOKS',
      image_count: 2
    }, {
      title: 'SLEEPING BABIES',
      slug: 'SleepingBabies',
      text: ['A panacea for those who need to relax a little<br>(in development)'],
      publisher: 'TRIBUTARY BOOKS',
      image_count: 2
    }, {
      title: 'FEARLESS COLOR GARDENS',
      slug: 'FearlessColorGardens',
      text: ['How to use wild, uninhibited color<br>to turn a garden into a work of art'],
      publisher: 'TIMBER PRESS',
      image_count: 2
    }, {
      title: "THE RANCHO GORDO HEIRLOOM BEAN GROWER'S GUIDE",
      slug: 'HeirloomBeans',
      text: ['Profiles of the fifty best beans to grow,<br>cook, and save'],
      publisher: 'TIMBER PRESS',
      image_count: 2
    }, {
      title: 'PROMISCUOUS PLANTS',
      slug: 'PromiscuousPlants',
      text: ['Guide to plants that spread, self-sow,<br>and overwinter'],
      publisher: 'TIMBER PRESS',
      image_count: 2
    }, {
      title: 'SAVE THE LAST BALL',
      slug: 'SaveLastBall',
      text: ['Memories, photographs, and essays from owners celebrating passed dogs<br>(in development)'],
      publisher: 'UNLEASHED BOOK DEVELOPMENT',
      image_count: 2
    }, {
      title: 'BACKYARD ROOTS',
      slug: 'BackyardRoots',
      text: ['An inspiring book featuring 35 urban farmers from Northern California, Oregon, Washington and British Columbia'],
      publisher: 'SKIPSTONE',
      image_count: 2
    }, {
      title: 'FROM TREE TO TABLE',
      slug: 'FromTreeToTable',
      text: ['Guide to growing backyard fruit trees<br>in the Pacific maritime climate'],
      publisher: 'MOUNTAINEERS BOOKS',
      image_count: 2
    }, {
      title: 'PACIFIC FEAST',
      slug: 'PacificFeast',
      text: ['Book highlighting the sustainable native bounty<br>of the West Coast'],
      publisher: 'SKIPSTONE',
      image_count: 2
    }, {
      title: 'BEAR COUNTRY',
      slug: 'BearCountry',
      text: ['Gift book featuring 125 full-color photographs of bears'],
      publisher: 'MOUNTAINEERS BOOKS',
      image_count: 2
    }, {
      title: 'EXPECTANT NUDE',
      slug: 'ExpectantNude',
      text: ['Collection of photography of pregnant women<br>(in development)'],
      publisher: 'UNLEASHED BOOK DEVELOPMENT',
      image_count: 2
    }, {
      title: 'NO BETTER TIME',
      slug: 'NoBetterTime',
      text: ['A guide to international aid and development to help readers make decisions about donating, volunteering, and advocacy', '(in development)'],
      publisher: 'TRIBUTARY BOOKS',
      image_count: 2
    }, {
      title: 'DIALOGUE WITH A DOCTOR',
      slug: 'DialogueDoctor',
      text: ['Q & A in layperson’s terms about cold and flu<br>(in development)'],
      publisher: 'TRIBUTARY BOOKS',
      image_count: 2
    }, {
      title: 'GREEN HOME PRIMER',
      slug: 'GreenHomePrimer',
      text: ['Ideas for building, remodeling, and buying green'],
      publisher: 'TIMBER PRESS',
      image_count: 2
    }, {
      title: 'THE ART OF ROUGH TRAVEL',
      slug: 'ArtOfRoughTravel',
      text: ['Abridged edition of a classic handbook<br>for explorers'],
      publisher: 'MOUNTAINEERS BOOKS',
      image_count: 2
    }, {
      title: 'CONTAINER INSPIRATION',
      slug: 'ContainerInspiration',
      text: ['Postcard series of container garden recipes'],
      publisher: 'WELLS-MEDINA NURSERY',
      image_count: 2
    }, {
      title: 'WILD WITH A GLUE GUN',
      slug: 'WildGlueGun',
      text: ['How-to book on starting a crafting group'],
      publisher: 'NORTH LIGHT BOOKS',
      image_count: 2
    }, {
      title: 'GETTING WILD',
      slug: 'GettingWild',
      text: ['Booklet packaged with high-tech glue gun describing its many possible uses'],
      publisher: 'COLD HEAT',
      image_count: 2
    }, {
      title: 'THE ARTISANS OF WHIDBEY ISLAND',
      slug: 'ArtisansWhidbey',
      text: ['Collection of biographies and work by artists<br>in the Puget Sound region (in development)'],
      publisher: '',
      image_count: 2
    }, {
      title: 'A LONG TREK HOME',
      slug: 'ALongTrekHome',
      text: ['Intimate account of a 4,000-mile human-powered expedition from Seattle to the Aleutian Islands'],
      publisher: 'MOUNTAINEERS BOOKS',
      image_count: 1
    }, {
      title: "PARENTS' LIVES, CHILDREN'S NEEDS",
      slug: 'ParentsChildren',
      text: ['Book offering advice on parenting effectively through developmental stages'],
      publisher: 'PERSONHOOD PRESS',
      image_count: 1
    }, {
      title: 'SHOWERED WITH LOVE',
      slug: 'ShoweredLove',
      text: ['Unique and eclectic book about making baby shower gifts (in development)'],
      publisher: 'UNLEASHED BOOK DEVELOPMENT',
      image_count: 2
    }, {
      title: 'TAJ',
      slug: 'Taj',
      text: ['Fictional love story from fifteenth-century India'],
      publisher: 'AMUNDSON DAVIS PUBLISHING',
      image_count: 1
    }
  ];

  app.layoutsLoaded = true;

}).call(this);
