// Generated by CoffeeScript 1.7.1
(function() {
  window.app = {
    image_prefix: './images/books/',
    crappyBrowser: navigator.appName === 'Microsoft Internet Explorer' && navigator.appVersion.indexOf('Windows') !== -1,
    navButName: ['home', 'books', 'misc', 'logos', 'clients', 'bio', 'contact', 'web'],
    navButton: [],
    setButtons: function() {
      var i;
      i = 0;
      while (i < this.navButName.length) {
        if (document.images[this.navButName[i]]) {
          if (this.navButName[i] === this.pageName) {
            document.images[this.navButName[i]].src = 'images/button/' + this.navButName[i] + '2.jpg';
          } else {
            document.images[this.navButName[i]].src = 'images/button/' + this.navButName[i] + '0.jpg';
          }
        }
        i++;
      }
    },
    changeButton: function(bName, bNum) {
      this.setButtons();
      if (bName !== this.pageName) {
        document.images[bName].src = 'images/button/' + bName + bNum + '.jpg';
      }
    },
    setIllustration: function(illoNumber) {
      var illustration;
      illustration = document.getElementById('illo' + illoNumber);
      if (eval("layouts[app.txtNum].leftIllo" + illoNumber)) {
        illustration.style.left = eval("layouts[app.txtNum].leftIllo" + illoNumber);
      }
      if (eval("layouts[app.txtNum].topIllo" + illoNumber)) {
        illustration.style.top = eval("layouts[app.txtNum].topIllo" + illoNumber);
      }
      if (eval("layouts[app.txtNum].widthIllo" + illoNumber)) {
        illustration.style.width = eval("layouts[app.txtNum].widthIllo" + illoNumber);
      }
      if (eval("layouts[app.txtNum].heightIllo" + illoNumber)) {
        illustration.style.height = eval("layouts[app.txtNum].heightIllo" + illoNumber);
      }
      if (eval("layouts[app.txtNum].srcIllo" + illoNumber)) {
        illustration.src = eval("layouts[app.txtNum].srcIllo" + illoNumber);
      }
      illustration.style.display = 'inline-block';
      return illustration;
    },
    loadImage: function() {
      var capTxt;
      if (layoutsLoaded === 'true') {
        capTxt = layouts[this.txtNum].name;
        if (document.getElementById(capTxt)) {
          this.capsOff();
          document.getElementById(capTxt).style.display = 'block';
        }
        if (this.crappyBrowser) {
          setTimeout('setIllustration(1)', 500);
          if (layouts[this.txtNum].srcIllo2) {
            setTimeout('setIllustration(2)', 1000);
            if (layouts[this.txtNum].srcIllo3) {
              setTimeout('setIllustration(3)', 1500);
            }
          }
        } else {
          this.setIllustration(1);
          if (layouts[this.txtNum].srcIllo2) {
            this.setIllustration(2);
            if (layouts[this.txtNum].srcIllo3) {
              this.setIllustration(3);
            }
          }
        }
      }
    },
    loadImage2: function() {
      var capPublisher, capText, capTitle, capTxt, i, image_count, publisher, slug, text, text1, text2, text3, title, two_digit_number, _i;
      if (this.layoutsLoaded) {
        capTxt = this.layouts[this.txtNum].name;
        title = this.layouts[this.txtNum].title;
        slug = this.layouts[this.txtNum].slug;
        text = '<p>' + this.layouts[this.txtNum].text.join('</p><p>') + '</p>';
        text1 = this.layouts[this.txtNum].text1;
        text2 = this.layouts[this.txtNum].text2;
        text3 = this.layouts[this.txtNum].text3;
        publisher = this.layouts[this.txtNum].publisher;
        image_count = this.layouts[this.txtNum].image_count;
        capTitle = document.getElementById('capTitle');
        capText = document.getElementById('capText');
        capPublisher = document.getElementById('capPublisher');
        capTitle.innerHTML = title;
        capText.innerHTML = text;
        capPublisher.innerHTML = publisher;
        for (i = _i = 1; _i <= 2; i = _i += 1) {
          if (i <= image_count) {
            two_digit_number = ('0' + this.txtNum).slice(-2);
            document.getElementById("illo" + i).style.visibility = 'visible';
            document.getElementById("illo" + i).src = "" + this.image_prefix + two_digit_number + "_" + slug + i + ".jpg";
          } else {
            document.getElementById("illo" + i).style.visibility = 'hidden';
            document.getElementById("illo" + i).style.height = '150px';
            document.getElementById("illo" + i).src = '';
          }
        }
      }
    },
    clearImages: function() {
      if (layouts[this.txtNum].srcIllo1) {
        document.getElementById('illo1').style.display = 'none';
        document.getElementById('illo1').src = './images/yellow.jpg';
      }
      if (layouts[this.txtNum].srcIllo2) {
        document.getElementById('illo2').style.display = 'none';
        document.getElementById('illo2').src = './images/yellow.jpg';
      }
      if (layouts[this.txtNum].srcIllo3) {
        document.getElementById('illo3').style.display = 'none';
        document.getElementById('illo3').src = './images/yellow.jpg';
      }
    },
    capsOff: function() {
      var capTxt, i;
      i = 0;
      while (i < layouts.length) {
        capTxt = layouts[i].name;
        document.getElementById(capTxt).style.display = 'none';
        i++;
      }
    },
    cycleIllos: function(direction) {
      var layoutsLength;
      this.clearImages();
      layoutsLength = layouts.length;
      if (direction === 'forward') {
        this.txtNum++;
        if (this.txtNum >= layoutsLength) {
          this.txtNum = 0;
        }
      } else {
        this.txtNum--;
        if (this.txtNum < 0) {
          this.txtNum = layoutsLength - 1;
        }
      }
      window.scrollTo(0, 0);
      this.loadImage();
    },
    cycleIllos2: function(direction) {
      var layoutsLength;
      layoutsLength = this.layouts.length;
      if (direction === 'forward') {
        this.txtNum++;
        if (this.txtNum >= layoutsLength) {
          this.txtNum = 0;
        }
      } else {
        this.txtNum--;
        if (this.txtNum < 0) {
          this.txtNum = layoutsLength - 1;
        }
      }
      window.scrollTo(0, 0);
      this.loadImage2();
    },
    displayImage: function(imageSrc) {
      document.getElementById('imageOverlay').style.display = 'block';
      document.getElementById('overlayImage').src = imageSrc;
    },
    killImage: function() {
      document.getElementById('imageOverlay').style.display = 'none';
    },
    ready: function() {
      var i;
      i = 0;
      while (i < this.navButName.length) {
        this.navButton[i] = new Image;
        this.navButton[i].src = 'images/button/' + this.navButName[i] + '0.jpg';
        this.navButton[i + this.navButName.length] = new Image;
        this.navButton[i + this.navButName.length].src = 'images/button/' + this.navButName[i] + '1.jpg';
        this.navButton[i + 2 * this.navButName.length] = new Image;
        this.navButton[i + 2 * this.navButName.length].src = 'images/button/' + this.navButName[i] + '2.jpg';
        i++;
      }
      return this.txtNum = 0;
    }
  };

  app.ready();

}).call(this);
